### ISSUE TITLE
Raven installs but doesn't load

### ISSUE THREAD

**Issue by EasternIndustries-IT** [The-Commit-Company/raven#1057]
Going through the default erpnext docker install.
Then running 
`bench get-app https://github.com/The-Commit-Company/Raven.git
bench install-app raven`

will install the site and shows on the frontend but going to `ip:port/raven` doesn't load
![image](https://github.com/user-attachments/assets/1e45bb27-0fb5-4fa6-bdc8-a68b28572c21)

Using the latest erpnext 15
![image](https://github.com/user-attachments/assets/57624521-ffb9-40d3-abfe-ec40120bd04a)

not sure why its not loading. Any help will be appreciated
Thank you,

**Comment by zaheer-srushty** [comment]
Can you do a `bench update` and share the logs from it? Are you self hosting or running this on Frappe Cloud?

**Comment by EasternIndustries-IT** [comment]
I am self hosting it. Im trying to build it completely and allow users to test before changing systems.
`bench update` shows this
`ERROR: Command 'git symbolic-ref -q --short HEAD' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/commands/update.py", line 59, in update
    update(
  File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", line 457, in update
    validate_branch()
  File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", line 644, in validate_branch
    branch = get_current_branch(app)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/utils/app.py", line 175, in get_current_branch
    return get_cmd_output("git symbolic-ref -q --short HEAD", cwd=repo_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 237, in get_cmd_output
    output = subprocess.check_output(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git symbolic-ref -q --short HEAD' returned non-zero exit status 128.
`

**Comment by zaheer-srushty** [comment]
From your bench folder, goto `apps/raven` and do a `git status`. Let me know what it says.

Also try uninstalling and installing it back again.

**Comment by EasternIndustries-IT** [comment]
Running git status
`On branch develop
Your branch is up to date with 'upstream/develop'.

nothing to commit, working tree clean`

After `bench uninstall-app raven ` and running `bench migrate` then restarting docker I get 
`An error occurred while installing raven: App raven not in apps.txt
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 445, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['frontend'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('raven',)
      force = False
      _install_app = <function install_app at 0x7f47d92a1ee0>
      filelock = <function filelock at 0x7f47d928b600>
      exit_code = 0
      site = 'frontend'
      app = 'raven'
      err = Exception('App raven not in apps.txt')
  File "apps/frappe/frappe/installer.py", line 279, in install_app
    raise Exception(f"App {name} not in apps.txt")
      name = 'raven'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f47d8923b00>
      sync_for = <function sync_for at 0x7f47d8740ae0>
      sync_customizations = <function sync_customizations at 0x7f47d9d20040>
      sync_fixtures = <function sync_fixtures at 0x7f47d8740e00>
      app_hooks = {'add_to_apps_screen': [{'name': 'raven', 'logo': '/assets/raven/raven-logo.png', 'title': 'Raven', 'route': '/raven', 'has_permission': 'raven.permissions.check_app_permission'}], 'additional_timeline_content': {'*': ['raven.api.raven_message.get_timeline_message_content']}, 'after_install': ['raven.install.after_install'], 'after_uninstall': ['raven.uninstall.after_uninstall'], 'app_description': ['Messaging Application'], 'app_email': ['support@thecommit.company'], 'app_include_css': ['raven.bundle.css'], 'app_include_js': ['raven.bundle.js'], 'app_license': ['AGPLv3'], 'app_logo': ['/assets/raven/raven-logo.png'], 'app_name': ['raven'], 'app_publisher': ['The Commit Company (Algocode Technologies Pvt. Ltd.)'], 'app_title': ['Raven'], 'app_version': ['1.7.0'], 'doc_events': {'User': {'after_insert': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_update': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_trash': ['raven.raven.doctype.raven_use...
      installed_apps = ['frappe', 'erpnext', 'raven']
builtins.Exception: App raven not in apps.txt`

**Comment by zaheer-srushty** [comment]
Did you install the app back after uninstall? There should be a apps.txt under your site folder. Once you install the app again, check if the text file has raven mentioned, else add it.

**Comment by EasternIndustries-IT** [comment]
I did try to reinstall by running 'bench install-app raven' I get the error above.
if I add raven in apps.txt then try and run 'bench install-app raven' results in 'App raven already installed'
after restart of backend and running 'bench install-app' the error in my previous comment is shown. and raven is removed from apps.txt Strangly enough localhost:8080/raven loads an error page but doesn't show the app as installed under erpnext
![image](https://github.com/user-attachments/assets/37978f0e-1370-4be2-be1d-05b9c7f540ab)

I see it on the home page 
![image](https://github.com/user-attachments/assets/16b1ece1-55f0-4b11-a2f6-d3b22688576e)

 but it doesn't show installed on about 
![image](https://github.com/user-attachments/assets/d40c4ba6-00b1-40e5-88cb-74f109ff4e4f)

**Comment by EasternIndustries-IT** [comment]
I was able to run 'bench uninstall-app raven'  and 'bench install-app' without error. 
Its now its still the same result going to ip:8080/raven

**Comment by zaheer-srushty** [comment]
Can you run `bench build --apps raven --production`

**Comment by EasternIndustries-IT** [comment]
This was the output of the command 

```$ bench build --apps raven --production
✔ Application Assets Linked


yarn run v1.22.22
$ node esbuild --production --apps raven --run-build-command
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
File                                                        Size

raven/dist/js/
└─ raven.bundle.YKUWCOAX.js                                 9.30 Kb

raven/dist/
└─ raven_chat.bundle.JD4JKU3E.js                            510.71 Kb

raven/dist/css/
└─ raven.bundle.NYUHCL32.css                                6.88 Kb

raven/dist/css-rtl/
└─ raven.bundle.XFDPH7GG.css                                6.89 Kb

 DONE  Total Build Time: 641.724ms


Running build command for raven
$ cd frontend && yarn build
$ vite build --base=/assets/raven/raven/ && yarn copy-html-entry
vite v4.5.3 building for production...
✓ 965 modules transformed.
[plugin:vite:reporter]
(!) /home/frappe/frappe-bench/apps/raven/frontend/src/components/feature/chat/ChatInput/Tiptap.tsx is dynamically imported by /home/frappe/frappe-bench/apps/raven/frontend/src/components/feature/chat/ChatMessage/ActionModals/EditMessageModal.tsx but also statically imported by /home/frappe/frappe-bench/apps/raven/frontend/src/components/feature/chat/ChatStream/ChatBoxBody.tsx, /home/frappe/frappe-bench/apps/raven/frontend/src/components/feature/threads/ThreadDrawer/ThreadMessages.tsx, dynamic import will not move module into another chunk.

[plugin:vite:reporter]
(!) /home/frappe/frappe-bench/apps/raven/frontend/src/pages/AddRavenUsersPage.tsx is dynamically imported by /home/frappe/frappe-bench/apps/raven/frontend/src/pages/MainPage.tsx but also statically imported by /home/frappe/frappe-bench/apps/raven/frontend/src/utils/channel/ChannelRedirect.tsx, dynamic import will not move module into another chunk.

rendering chunks (27)...
PWA v0.20.1
WARNING: "theme_color" is missing from the web manifest, your application will not be able to be installed
../raven/public/raven/manifest.webmanifest                         0.77 kB
../raven/public/raven/index.html                                  10.94 kB │ gzip:   1.33 kB
../raven/public/raven/assets/CalSans-SemiBold-d3e38c94.woff2      40.93 kB
../raven/public/raven/assets/CalSans-SemiBold-c8c75bb7.woff       52.50 kB
../raven/public/raven/assets/CalSans-SemiBold-ed3461b0.ttf       148.96 kB
../raven/public/raven/assets/MessageItem-554f4ebc.css              0.17 kB │ gzip:   0.14 kB
../raven/public/raven/assets/JoinChannelBox-cb4c4755.css           2.41 kB │ gzip:   0.84 kB
../raven/public/raven/assets/index-7c1f9858.css                  741.71 kB │ gzip:  89.27 kB
../raven/public/raven/assets/useRavenSettings-2a6fbde1.js          0.23 kB │ gzip:   0.18 kB
../raven/public/raven/assets/PageHeader-885f8ccb.js                0.52 kB │ gzip:   0.33 kB
../raven/public/raven/assets/validations-49f09b53.js               0.68 kB │ gzip:   0.43 kB
../raven/public/raven/assets/AuthContainer-46179a27.js             0.96 kB │ gzip:   0.53 kB
../raven/public/raven/assets/SavedMessages-37e2b262.js             1.12 kB │ gzip:   0.63 kB
../raven/public/raven/assets/MessageBox-49a27fa3.js                1.24 kB │ gzip:   0.64 kB
../raven/public/raven/assets/Settings-9408e83c.js                  1.92 kB │ gzip:   0.83 kB
../raven/public/raven/assets/LoginWithEmail-759eebdb.js            2.11 kB │ gzip:   1.05 kB
../raven/public/raven/assets/MobileInputActions-04f97046.js        2.22 kB │ gzip:   0.97 kB
../raven/public/raven/assets/ForgotPassword-a28b8fa3.js            2.29 kB │ gzip:   1.16 kB
../raven/public/raven/assets/SetCustomStatusContent-1545c545.js    2.35 kB │ gzip:   1.19 kB
../raven/public/raven/assets/SignUp-a03b7891.js                    2.63 kB │ gzip:   1.19 kB
../raven/public/raven/assets/Threads-2a04e05e.js                   3.24 kB │ gzip:   1.35 kB
../raven/public/raven/assets/FrappeHR-ac6adc9c.js                  3.25 kB │ gzip:   1.38 kB
../raven/public/raven/assets/AddUsers-3bd5355d.js                  3.39 kB │ gzip:   1.62 kB
../raven/public/raven/assets/AddMembersDropdown-412091a6.js        3.61 kB │ gzip:   1.61 kB
../raven/public/raven/assets/CreatePoll-bd830e15.js                4.18 kB │ gzip:   1.77 kB
../raven/public/raven/assets/GIFPicker-1c1c5faa.js                 4.48 kB │ gzip:   1.54 kB
../raven/public/raven/assets/Login-b88ba3dd.js                     6.18 kB │ gzip:   2.30 kB
../raven/public/raven/assets/ThreadDrawer-dd40bd24.js              6.79 kB │ gzip:   2.87 kB
../raven/public/raven/assets/ViewFilesContent-d72acb5a.js          7.60 kB │ gzip:   2.64 kB
../raven/public/raven/assets/downshift.esm-b622695a.js            29.41 kB │ gzip:   9.89 kB
../raven/public/raven/assets/ImageViewer-6d0ca459.js              30.32 kB │ gzip:   9.60 kB
../raven/public/raven/assets/JoinChannelBox-68a62dbd.js           57.54 kB │ gzip:  16.58 kB
../raven/public/raven/assets/ChatSpace-46a00b3c.js                58.64 kB │ gzip:  14.97 kB
../raven/public/raven/assets/MessageItem-e96ac331.js             731.68 kB │ gzip: 231.51 kB
../raven/public/raven/assets/index-43bf8b12.js                   950.58 kB │ gzip: 289.51 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

PWA v0.20.1
Building public/sw.js service worker ("es" format)...
vite v4.5.3 building for production...
✓ 75 modules transformed.
../raven/public/raven/sw.mjs  100.71 kB │ gzip: 21.42 kB
✓ built in 400ms

PWA v0.20.1
mode      injectManifest
format:   es
precache  33 entries (2621.48 KiB)
files generated
  ../raven/public/raven/sw.js
✓ built in 15.52s
$ cp ../raven/public/raven/index.html ../raven/www/raven.html
Done in 18.23s.
Compiling translations for raven```

ip:8080/raven did not load after running the command.
The errors from the web browser inspect is below.
![image](https://github.com/user-attachments/assets/6212624b-271b-48c1-a352-166bbdff2a34)

**Comment by zaheer-srushty** [comment]
It looks the build process has completed successfully....I believe this has to do with how bench is started/deployed....the issue you are facing is that the index JS file is not being loaded for some reason. Check your **nginx** file if you are in prod or do a **bench start/restart** to see if that fixes it.

This is not a Raven issue I guess.

**Comment by EasternIndustries-IT** [comment]
Nginx isn't used. I am trying to get everything installed and testing before configuring it. Most likely going to use caddy.
I'm using the default pwd.yml file for the repo with minor changes to volumes. bench start or restart doesn't work. creating a new site is inaccessible probably do to backend docker not having access to the /etc/host file.

[pwd.yml file]
```
version: '3'
services:
  backend:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
  configurator:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - '-c'
    command:
      - >
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache
        "redis://$$REDIS_CACHE"; bench set-config -g redis_queue
        "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio
        "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port
        $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      REDIS_CACHE: 'redis-cache:6379'
      REDIS_QUEUE: 'redis-queue:6379'
      SOCKETIO_PORT: '9000'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  create-site:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: none
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - 'assets:/home/frappe/frappe-bench/sites/assets'
    entrypoint:
      - bash
      - '-c'
    command:
      - >
        wait-for-it -t 120 db:3306; wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379; export start=`date +%s`; until [[
        -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host //
        empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done; echo "sites/common_site_config.json found"; bench new-site
        --no-mariadb-socket --admin-password=admin --db-root-password=admin
        --install-app erpnext --set-default frontend;
  db:
    image: 'mariadb:10.6'
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--skip-innodb-read-only-compressed'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - 'db-data:/var/lib/mysql'
  frontend:
    image: 'frappe/erpnext:v15.35.1'
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: 'backend:8000'
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: 'websocket:9000'
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
    ports:
      - '8080:8080'
  queue-long:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'long,default,short'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
  queue-short:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - '--queue'
      - 'short,default'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
  redis-queue:
    image: 'redis:6.2-alpine'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'redis-queue-data:/data'
  redis-cache:
    image: 'redis:6.2-alpine'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - 'redis-cache-data:/data'
  scheduler:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
  websocket:
    image: 'frappe/erpnext:v15.35.1'
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
      # - '/assets:/home/frappe/frappe-bench/sites/assets'
volumes:
  # assets:
  #   driver: local
  #   driver_opts: 
  #     type: none
  #     device: '${PWD}/assets'
  #     o: bind
  db-data:
    driver: local
    driver_opts: 
      type: none
      device: '${PWD}/db-data'
      o: bind
  redis-queue-data:
    driver: local
    driver_opts: 
      type: none
      device: '${PWD}/redis-queue-data'
      o: bind
  redis-cache-data:
    driver: local
    driver_opts: 
      type: none
      device: '${PWD}/redis-cache-data'
      o: bind
  redis-socketio-data:
    driver: local
    driver_opts: 
      type: none
      device: '${PWD}/redis-socketio-data'
      o: bind
  sites:
    driver: local
    driver_opts: 
      type: none
      device: '${PWD}/sites'
      o: bind
  logs: 

```
